version: '3'
services:
  ui:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/matchie
      - PORT=5000      

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
