services:
  ui:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - mynetwork

  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/matchie
      - PORT=5000      
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  mongo-data: